config {
 name: 'celebrus_config',
 type: "table",
 description: "Celebrus configuration export.",
 uniqueKey: ["uuid"],
 schema: "dataform_reporting",
 tags: ['celebrus'],
 bigquery: {
   clusterBy: ["config"],
 }
}

WITH xml_data AS (
  ${helpers.getXmlData('AVERO_ACHMEA', false)}
  ${helpers.getXmlData('CB_KLANTDOMEIN')}
  ${helpers.getXmlData('CB_PARTICULIER')}
  ${helpers.getXmlData('CBA_ZAKELIJK')}
  ${helpers.getXmlData('GLOBAL')}
  ${helpers.getXmlData('MEDEWERKERS_DESKTOP')}
  ${helpers.getXmlData('MOBIELE_APPS')}
  ${helpers.getXmlData('ROADGUARD')}
)
SELECT
  config,
  JSON_VALUE(xml_string, '$.processing.graph.uuid') AS uuid,
  JSON_VALUE(xml_string, '$.processing.graph.name') AS name,
  JSON_VALUE(xml_string, '$.processing.graph.eventType') AS eventType,
  JSON_VALUE(xml_string, '$.processing.graph.partition.partitionType') AS partitionType,
  -- Nodes
  ${helpers.getNode('name')},
  ${helpers.getNode('eventSource')},
  ${helpers.getNode('eventType')},
  ${helpers.getNestedNode('attributePathName', 'match.constraints.valueconstraint')},
  ${helpers.getNestedNode('operator', 'match.constraints.valueconstraint')},
  --JSON_QUERY(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.value.""'),
  CASE
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.value.""') IS NOT NULL THEN ARRAY( SELECT JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.operator'))
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint[0].value.""') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(IFNULL(JSON_VALUE(nodeArr, '$.value.""'), ''))
  FROM
    UNNEST(JSON_QUERY_ARRAY(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint')) AS nodeArr)
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint.value.""') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(IFNULL(JSON_VALUE(nodeArr, '$.match.constraints.valueconstraint.value.""'), ''))
  FROM
    UNNEST(JSON_QUERY_ARRAY(xml_string, '$.processing.graph.nodeDefinitions.matchNode')) AS nodeArr)
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint[0].value.""') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(IFNULL(JSON_VALUE(nodeArr, '$.value.""'), ''))
  FROM
    UNNEST(
      (SELECT
        JSON_QUERY_ARRAY(JSON_QUERY(xml_string, '$.processing.graph.nodeDefinitions.matchNode'), '$[0].match.constraints.valueconstraint'))
    ) AS nodeArr)
   WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint[0].value[0].""') IS NOT NULL THEN (
      SELECT
        ARRAY_AGG(JSON_QUERY(nodeArr, '$.""'))
      FROM
        UNNEST ( (
          SELECT
            ARRAY_CONCAT_AGG(JSON_QUERY_ARRAY(nodeArr, '$.value'))
          FROM
            UNNEST( (
              SELECT
                JSON_QUERY_ARRAY(JSON_QUERY(xml_string, '$.processing.graph.nodeDefinitions.matchNode'), '$[0].match.constraints.valueconstraint')) ) AS nodeArr) ) AS nodeArr )
  END
    AS nodeMatchOperator,
FROM
  xml_data

/* BACKUP SQL
  JSON_STRIP_NULLS(JSON_ARRAY(
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[1].name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[2].name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[3].name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[4].name'),
  JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[5].name')
  )) AS nodeNames,
  CASE
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.name') IS NOT NULL THEN ARRAY( SELECT JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.name'))
    ELSE (
  SELECT
    ARRAY_AGG(JSON_VALUE(nodeNamesArr, '$.name'))
  FROM
    UNNEST(JSON_QUERY_ARRAY(xml_string, '$.processing.graph.nodeDefinitions.matchNode')) AS nodeNamesArr)
  END
    AS nodeNames,
  CASE
  WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.operator') IS NOT NULL THEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.operator')
  WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint[0].operator') IS NOT NULL THEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint[0].operator')
  WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint.operator') IS NOT NULL THEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint.operator')
  ELSE JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint[0].operator')
  END AS nodeMatchOperator,
  CASE
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.operator') IS NOT NULL THEN ARRAY( SELECT JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint.operator'))
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint[0].operator') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(JSON_VALUE(nodeArr, '$.operator'))
  FROM
    UNNEST(JSON_QUERY_ARRAY(xml_string, '$.processing.graph.nodeDefinitions.matchNode.match.constraints.valueconstraint')) AS nodeArr)
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint.operator') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(IFNULL(JSON_VALUE(nodeArr, '$.match.constraints.valueconstraint.operator'), ''))
  FROM
    UNNEST(JSON_QUERY_ARRAY(xml_string, '$.processing.graph.nodeDefinitions.matchNode')) AS nodeArr)
    WHEN JSON_VALUE(xml_string, '$.processing.graph.nodeDefinitions.matchNode[0].match.constraints.valueconstraint[0].operator') IS NOT NULL THEN (
  SELECT
    ARRAY_AGG(IFNULL(JSON_VALUE(nodeArr, '$.operator'), ''))
  FROM
    UNNEST(
      (SELECT
        JSON_QUERY_ARRAY(JSON_QUERY(xml_string, '$.processing.graph.nodeDefinitions.matchNode'), '$[0].match.constraints.valueconstraint'))
    ) AS nodeArr)
  END
    AS nodeMatchOperator,
*/