config {
 name: 'celebrus_config_extractors',
 type: "table",
 description: "Celebrus configuration export.",
 schema: "dataform_reporting",
 tags: ['celebrus', 'daily']
}

SELECT *
FROM ${ref('celebrus_config_extractors_1_no_nesting')}
UNION ALL
SELECT *
FROM ${ref('celebrus_config_extractors_2_nesting_on_extractor')}
UNION ALL
SELECT *
FROM ${ref('celebrus_config_extractors_3_nesting_on_matchnode')}
UNION ALL
SELECT *
FROM ${ref('celebrus_config_extractors_4_nesting_on_all')}