config { 
  type: "operations",
  name: "celebrus_journey_funnels_external",
  schema: "dataform_sources",
  hasOutput: true
}

CREATE OR REPLACE EXTERNAL TABLE `centraal-beheer-248507.dataform_sources.celebrus_journey_funnels_external`
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1-3AUUEBCor0CKjS1ym7Zt0HExl9m117flMPz1CKoH-0'],
  sheet_range = 'Blad1!A1:F',
  skip_leading_rows = 1
);
