config {
 name: 'celebrus_config_json',
 type: "table",
 description: "Celebrus configuration export.",
 schema: "dataform_sources",
 tags: ['celebrus', 'daily'],
 bigquery: {
   clusterBy: ["config"],
 },
 dependencies: ["celebrus_config_nodes_snapshot", "celebrus_config_scenarios_snapshot", "celebrus_config_values_snapshot"]
}

${helpers.getXmlData('AVERO_ACHMEA', false)}
${helpers.getXmlData('CB_KLANTDOMEIN')}
${helpers.getXmlData('CB_PARTICULIER')}
${helpers.getXmlData('CBA_ZAKELIJK')}
${helpers.getXmlData('GLOBAL')}
${helpers.getXmlData('MEDEWERKERS_DESKTOP')}
${helpers.getXmlData('MOBIELE_APPS')}
${helpers.getXmlData('ROADGUARD')}

post_operations {
  ${helpers.deleteQuery('AVERO_ACHMEA')}
  ${helpers.deleteQuery('CB_KLANTDOMEIN')}
  ${helpers.deleteQuery('CB_PARTICULIER')}
  ${helpers.deleteQuery('CBA_ZAKELIJK')}
  ${helpers.deleteQuery('GLOBAL')}
  ${helpers.deleteQuery('MEDEWERKERS_DESKTOP')}
  ${helpers.deleteQuery('MOBIELE_APPS')}
  ${helpers.deleteQuery('ROADGUARD')}
}