const DATABASE = 'centraal-beheer-248507';
const DATASET = 'dataform_sources';
const XML_PREFIX = 'celebrus_xml_config_';
const XML_AVERO_ACHMEA = 'avero_achmea';
const XML_CB_KLANTDOMEIN = 'cb_klantdomein';
const XML_CB_PARTICULIER = 'cb_particulier';
const XML_CBA_ZAKELIJK = 'cba_zakelijk';
const XML_GLOBAL = 'global';
const XML_MEDEWERKERS_DESKTOP = 'medewerkers_desktop';
const XML_MOBIELE_APPS = 'mobiele_apps';
const XML_ROADGUARD = 'roadguard';
module.exports = {DATABASE, DATASET, XML_PREFIX, XML_AVERO_ACHMEA, XML_CB_KLANTDOMEIN, XML_CB_PARTICULIER, XML_CBA_ZAKELIJK, XML_GLOBAL, XML_MEDEWERKERS_DESKTOP, XML_MOBIELE_APPS, XML_ROADGUARD}